### ISSUE TITLE
Only use XSLT/XPath 1.0 compatible checks (get rid of xs:decimal)

### ISSUE THREAD

**Issue by ojundt** [SimplerInvoicing/validation#12]
Currently the schematron files contain conditions that make use of XPath 2.0 functions/types (`xs:decimal`) that require the resulting XSL files to be used with a XPath 2.0 compatible library. Unfortunately the support for XPath 2.0 is still very limited. Afaik the SAXON XSLT and XQuery processor in Java and .NET is the only mature library that does support it.

Since SimplerInvoicing requires everyone to validate their documents before sending them this means that everyone is required to add Java and Saxon to their ecosystem. This doesn't make sense if your application is running in Ruby or example.

We can improve the adoption of proper validation if we limit ourselves to XPath 1.0. As far as I can see `xs:decimal` is currently the only XPath 2.0-only feature being used. If this could be replaced, this issues should be fixed.

**Comment by tjeb** [comment]
Ok, so at the time I thought I was the only one that had a problem with introducing XSLT2 for this, but there was no other pushback so I figured I had to live with it. I ended up writing a minimal Java tool to do the translation for my other software, but I can imagine this isn't a good solution for everyone.

The short story is that the PEPPOL artefacts these are based on moved to 2 some time ago, citing rounding issues with floating point numbers, and needing xs:decimal to fix it. There were a number of workarounds already in place (like dividing and multiplying by 100) but apparently those were not enough.

TBH, I feel uncomfortable deviating from the source artefacts too much. Changing calculations also needs additional testing, for both rounding itself and compatibility with PEPPOL (though if rounding itself is tested well compatibility should be ok). We already have a number of deviations from PEPPOL in 1.1 and 1.2, but for the upcoming 2.0 (I will merge release candidate artefacts shortly) there should no longer be any, only additional checks for NLCIUS-specific rules on EN-16931.

**Comment by ojundt** [comment]
Hi @tjeb, thanks for your explanation. I understand now why working with `number()` and dividing/multiplying by 100 is a big pain. I just came across a SI UBL 1.1 schematron rule failing because of rounding errors in `number()`:
```
Nokogiri::XML('<Foo>1.57</Foo>').xpath('number(/Foo)') => 1.5699999999999998
```
There are also alot of problems found on the web due to similar problems. `xs:decimal` is the only good fix and you should stick to it. One might only hope that the XPath2.0 support will improve in the future. In the meantime we solved it by building a small Java servlet based webservice that does the validations for us outside of our Ruby environment.
