### ISSUE TITLE
Rarely possible to fulfill rule BR-NL-2

### ISSUE THREAD

**Issue by ojundt** [SimplerInvoicing/validation#14]
With the SI UBL 2.0 RC1 schematron we get alot of errors due to rule BR-NL-2:
```
[BR-NL-2] For suppliers in the Netherlands, the invoice MUST contain either the buyer reference (cbc:BuyerReference) or the order reference (cac:OrderReference/cbc:ID)
```
Having an order reference is a rare scenario. Most of the invoices sent by our users at Moneybird only have an invoice id. Are there any recommendations how to deal with this problem? If this rule makes it into the final version of SI UBL 2.0 it would mean we can only send a small ratio of invoices through SI.

**Comment by tjeb** [comment]
This rule came straight from the 'gebruikersinstructie basisfactuur' at https://stpe.nl/media/stpe.nl-gebruiksinstructie-basisfactuur-v1.0.pdf.

Not sure if this helps, but they added a section about this (section 7.2, translation mine):

"The core invoice has many references to documents and objects. These can and may only be present when they are applicable. However, to make automatic processing easier, it is mandatory to fill in either the purchase order number (BT-13), or the buyer reference (BT-10). The buyer reference field contains a reference provided by the buyer when ordering, or (when it has not been supplied) a reference that makes it possible for the buyer to approve the invoice (such as the name of the ordering buyer)."

I'll see if someone present during the creation of that requirement can pitch in.

**Comment by WvandenBerg** [comment]
Hello, I was involved in the making of the NLCIUS. 

I understand most of the e-invoices Monybird processes have only an invoice ID and no other references. I recommend Moneybird to fill BT-10 with some data that the receiving party can use to verify the invoices. Examples are: date of delivery or the name of seller/contact person. Usually the buyer party (receiving party) indicates to the seller what information they expect to carry out this verification. 

Is this helpful?

**Comment by wimkok** [comment]
Is this rule specific for the goverment? In that case you can check if customer is using OIN.

Putting fake information in a field feels like a bad design.

**Comment by jdiepenmaat** [comment]
> Hello, I was involved in the making of the NLCIUS.
> 
> I understand most of the e-invoices Monybird processes have only an invoice ID and no other references. I recommend Moneybird to fill BT-10 with some data that the receiving party can use to verify the invoices. Examples are: date of delivery or the name of seller/contact person. Usually the buyer party (receiving party) indicates to the seller what information they expect to carry out this verification.
> 
> Is this helpful?

Yes and No. Honestly, I have to agree with @wimkok. 

As a founding member of the SimplerInvoicing foundation, we had this discussion before. The far majority of entities in the Netherlands are companies under 10 employees (roughly 800.000). We have done extensive analysis over this group and there's rarely a need for a `Buyer reference` or an `Order reference`. These companies just know what they've ordered and check the invoice with their eyes, reading the lines. They even don't register what they've ordered, there is no need for matching purchase orders with invoices at all.

As Moneybird, we do have an interface that supports entering an `order reference` / `PO`. But it is less than 1% of our customers that use the field when they create an invoice and send it to a customer. Almost all the invoices that have the `order reference` filled are being delivered to governments, semi governments or large corporates.

The important point is that "I recommend Moneybird to fill BT-10 with some data that the receiving party can use to verify the invoices." feels like a bad design, like @wimkok states. 
It certainly does not sound a good idea to make the `order reference` field mandatory in our interface, as it will confuse many entrepreneurs. Hence, we would probably end up filling the "receiving party's name" or the "invoice number" in the `order reference` if the field `order reference` is left empty by the end user.

We basically end up with a lot of fluffy information in our database as any party will put random stuff in the field. The customer receives their invoices also via PEPPOL in Moneybird and will see "Order reference: Jan Jansen". It doesn't make sense to me. And that's not why standards exist.

So, I would strongly urge to withdraw this change in the move from SI 1.2 towards 2.0. Please don't make `order reference` field mandatory. I can support @wimkok's comment to make it mandatory when the receiver entity in the SMP is using an OIN, but I'm not sure how other software vendors are willing to implement this.

**Comment by johanschaeffer** [comment]
I fully agree with @wimkok and @jdiepenmaat on this topic.

The NLCIUS1.0 is not consistent on this topic. The remark on page 47, BT-10 states the reference is only mandatory when it has been communicated. "...leveranciers (BT-40 = NL) verplicht **als een referentie is gecommuniceerd**, bijv. een routecode.  OF BT-10 OF BT-13 moet door Nederlandse leveranciers verplicht gevuld zijn."

Additionally it's very complicated to make one of two fields (BT-10 OR BT-13) mandatory. We should stay with the business rule of SI1.2 by having one field for the reference. This will only add extra work for the receiving software, because two fields need to be processed for only one reference.

**Comment by tjeb** [comment]
Additionally, for a receiving processor, figuring out if the value makes any sense (in the case where the majority of senders just put in anything to have it non-empty) might even be harder than adding a check whether it exists and giving it an internal value if it doesn't.

But anyway, I currently see three options for the SI rules: 1. stick to the rules as is, 2. get this rule dropped from NLCIUS, and 3. deviate from NLCIUS regarding this rule.

1. Going by this discussion, it seems this option wouldn't get much support
2. I believe there is an NLCIUS CAB meeting soon, and it sounds like this would be a good point for the agenda. Perhaps it can be lifted to a business-level requirement (TBH it sounds like it should be on that level anyway), but I don't think MLR's are well-supported enough to cover what I believe to be the use-cases yet, so this would mean that automated checking and handling will probably not be feasible just yet. Another option would be to drop it altogether, of course.
3. If 1 and 2 are a no-go, we can consider relaxing the rule for SI-UBL. But this would mean that, as the SI community, we would already be deviating from the NLCIUS, going against earlier decisions of the community regarding following it. On the technical level there might be issues too (we already see this with current versions); when receivers are more strict than senders regarding certain requirements, errors bubble up to users that they don't understand (or, in some cases, can't even see). I don't think anyone wants any more of that.

Presuming 1 is out of the question for now, I propose we go aim for 2, and consider 3 as a fallback.

**Comment by jdiepenmaat** [comment]
@tjeb thanks for taking the time on this one! I sent an e-mail with the request to talk about this issue during the NLCIUS CAB meeting on the 28th.

**Comment by Michiel-s** [comment]
Hi all, this issue will indeed be discussed during the meeting next week.

A comment from my perspective, this BR-NL-2 is introduced because of explicit request from participants during NLCIUS process.
Also keep in mind that PEPPOL BIS v3 has exactly the same rule: [PEPPOL-EN16931-R003](http://docs.peppol.eu/poacc/billing/3.0/rules/PEPPOL-EN16931-R003/).

**Comment by tjeb** [comment]
Cleaning up open issues; should the CAB decide to update this rule, we can open a new one.
