### ISSUE TITLE
Optional cbc:CustomizationID is giving fatal when missing

### ISSUE THREAD

**Issue by wimkok** [SimplerInvoicing/validation#15]
XSLT
[BII2-T10-R001] An invoice MUST have a customization identifier

https://stpe.t4smm.nl/#/TreeView/Element_1528564882_00008632
BR-1 - An Invoice shall have a Specification identifier (BT-24).

**Comment by tjeb** [comment]
Seems to be either an error, or at least very unclear, on t4smm... in the most general form of UBL 2.1 the field is optional, but not in EN-16931, PEPPOL BIS v3, or the NLCIUS.
