### ISSUE TITLE
SI 2.0 RC1 test files

### ISSUE THREAD

**Issue by phax** [SimplerInvoicing/validation#16]
Hi guys,
some test files (Invoice and Credit note) for the 2.0 RC1 Schematrons would be super.
Thanks

**Comment by tjeb** [comment]
We have a number of test files in a different repository: https://github.com/SimplerInvoicing/testset (SI-UBL 2.0 files at https://github.com/SimplerInvoicing/testset/tree/master/SI-UBL-2.0 )

Of course, if you are missing anything in particular, let me know.

I'll add a reference to that in the readme.

**Comment by phax** [comment]
Thanks a lot - a reference would be great :)

**Comment by phax** [comment]
Excellent - even a positive CreditNote is contained :)
SI 2.0 RC1 will be part of ph-bdve 5.1.2.
