### ISSUE TITLE
Mimecode rejected in SI1.2 xslt but listed in http://www.iana.org/assignments/media-types/media-types.xhtml

### ISSUE THREAD

**Issue by wimkok** [SimplerInvoicing/validation#17]
path: si:Invoice/si:AdditionalDocumentReference/si:Attachment/si:EmbeddedDocumentBinaryObject/@mimeCode
May containg codes from http://www.iana.org/assignments/media-types/media-types.xhtml

But fatal Error: [CL-T10-R008]-For Mime code in attribute use MIMEMediaType. is thrown for mimeCode="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

Is the list in XSLT up to date?

**Comment by tjeb** [comment]
Hmz, these parts of the rules have always been based on PEPPOL BIS v2, which does not include all the ones defined by IANA (but rather a subset as defined by CEN). Granted, we haven't updated the peppol part to the latest release, but the mime types haven't changed there, afaict. So there seems to be a bit of a disconnect between the documentation and the actual rules in place. I have not yet made up my mind what to do about that. Side note, for EN, this list seems to have been reduced quite drastically, down to 6 types...

**Comment by tjeb** [comment]
Cleaning up old issues; if it wasn't clear, the general consensus seems to be to leave the lists as specified for now, and defer to either CEN or STPE to discuss additional types.
