### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by WvandenBerg** [SimplerInvoicing/validation#19]
The EN validation artifacts do not check whether a Purchase order reference (BT-13) exists on invoice level when a Referenced purchase order line reference (BT-132) is used on line level. 

I've brought this up with the people of the EN artifacts but they quickly dismissed it, see: https://github.com/CenPC434/validation/issues/154

I suggest we add this rule check to our NLCIUS, to strengthen the validation service of NLCIUS compliant e-invoices.

**Comment by tjeb** [comment]
Thanks, I think it makes sense, and have put this up as a request for change at the NLCIUS working group.
