### ISSUE TITLE
PaymentMeansTypeCode

### ISSUE THREAD

**Issue by PPotappel** [SimplerInvoicing/validation#20]
Op de STPEsite staat dat deze code voor Nederlandse Suppliers wat anders **MAG** zijn dan de standaard (https://stpe.t4smm.nl/#/TreeView/Element_1528564881_00357966) 
In de validaties (BR-NL-12) staat dat je als NL-supplier deze codes **VERPLICHT** moet gebruiken.
Wat is juist?

**Comment by tjeb** [comment]
Ik interpreteer dat als 'mag uitsluitend uit een van de volgende waarden bestaan' (want waarom zou je ze anders noemen). Ik ben het na aan vragen of mijn interpretatie daar incorrect is.

**Comment by remcoros** [comment]
De Nederlandse vertaling voor 'SHALL' is hier 'mag', maar is incorrect volgens RFC2119:

https://www.ietf.org/rfc/rfc2119.txt

    MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification.

    MAY   This word, or the adjective "OPTIONAL", mean that an item is truly optional.

Dus dit had 'mag uitsluitend' of 'moet' moeten zijn.

**Comment by PPotappel** [comment]
OK. En de definitie van NL-supplier is dan een partij waarvan de identifier NL:KVK, NL:VAT of NL:OIN is? Alle andere partijen **moeten** de andere codelijst gebruiken?

**Comment by tjeb** [comment]
Ik heb eindelijk terug gehoord van de mensen van de STPE; ze bedoelen inderdaad dat het een van deze waarden moet zijn.

NL-supplier wordt gedefinieerd door het veld BT-40 (Seller Country Code, ubl:Invoice/cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cac:Country/cbc:IdentificationCode).
