### ISSUE TITLE
Code BR-GA-0 is not in error text in si-ubl-2.0-ext-gaccount.sch

### ISSUE THREAD

**Issue by wimkok** [SimplerInvoicing/validation#25]
Other error text contain the errorcode. But not for BR-GA-0

**Comment by WvandenBerg** [comment]
Indeed. The [error text of BR-GA-0](https://github.com/SimplerInvoicing/validation/blob/d278e10ddffb0885245b76293c1001e26943489f/schematron/si-ubl-2.0-ext-gaccount.sch#L39) is missing `[BR-GA-0]`. Should be added for clarity, just like with the other rules.
