### ISSUE TITLE
Consider creating a check on //cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:ID

### ISSUE THREAD

**Issue by wimkok** [SimplerInvoicing/validation#26]
Number used for:
//cac:PaymentMeans[cbc:ID = 'GACCOUNT']/cac:PayeeFinancialAccount/cbc:ID
has a specific format (NL15ABNA09900000000).

See:
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/internationaal/personeel/u_bent_niet_in_nederland_gevestigd_loonheffingen_inhouden/wanneer_moet_u_loonheffingen_inhouden1/u_bent_inhoudingsplichtig1/u_zendt_of_leent_personeel_uit_of_u_detacheert_personeel_in_nederland/g-rekening

'Een g-rekeningnummer bevat altijd de cijfers 099 op de 3 posities direct na de uit 4 letters bestaande bankcode.'

**Comment by RobinTNO** [comment]
Because changes concerning the NLCIUS and G-rekening extension will be discussed within the STPE working group, this change is moved to https://stpe.semantic-treehouse.nl/#/Change_32_request/ChangeRequest_1589283420_00947972.
