### ISSUE TITLE
Bug in BR-NL-10 test [SI-UBL-2.0-NLCIUS]

### ISSUE THREAD

**Issue by WvandenBerg** [SimplerInvoicing/validation#27]
I suspect a bug in schematron/si-ubl-2.0/si-ubl-2.0-nlcius.sch.
More specifically in the [test of BR-NL-10](https://github.com/SimplerInvoicing/validation/blob/2b4dc0c7ba42a965b07b59ffc94a687e5649167b/schematron/si-ubl-2.0/si-ubl-2.0-nlcius.sch#L63).

The way this test is implemented implies that the element in question is optional. This would be an incorrect interpretation of the BR-NL-10 as written in the NLCIUS spec. To be fair, the relevant text in the NLCIUS spec. is unclear, but the comment at BT-47 in the same document confirms that this element is meant to be mandatory

**Comment by tjeb** [comment]
Do you have an example of a document that incorrectly passes this test? Simply leaving out BT-47 like in https://github.com/SimplerInvoicing/testset/blob/master/SI-UBL-2.0/SI-UBL-2.0_BR-NL-10_error_customer_no_companyid.xml does not pass validation (if buyer and supplier are both in NL).

**Comment by WvandenBerg** [comment]
Thanks for pointing that out. After going through the code and the BR-NL-10 text again, I think this was a misunderstanding on my part. Apologies.
