### ISSUE TITLE
Bug in BR-NL-11 test [SI-UBL-2.0-NLCIUS]

### ISSUE THREAD

**Issue by WvandenBerg** [SimplerInvoicing/validation#28]
I suspect a bug in schematron/si-ubl-2.0/si-ubl-2.0-nlcius.sch.
More specifically in the [test of BR-NL-11](https://github.com/SimplerInvoicing/validation/blob/2b4dc0c7ba42a965b07b59ffc94a687e5649167b/schematron/si-ubl-2.0/si-ubl-2.0-nlcius.sch#L73).

The comparison operator should be **`&gt;=`** instead of `&lt;=` like it is now. 
After all, the test is meant to check whether the PayableAmount is a positive amount or, if not, a PaymentMeans is specified.

**Comment by tjeb** [comment]
Am I reading the spec incorrectly? "BG-16 must be given if the payment is from customer to supplier", which would mean if the amount is positive, right?

**Comment by WvandenBerg** [comment]
You are right; I'm mistaken. In that case the test makes use of the correct comparison operator. Apologies

**Comment by tjeb** [comment]
No problem, thanks for taking a close look :)
