### ISSUE TITLE
Check for [BR-NL-7] is not done with string

### ISSUE THREAD

**Issue by wimkok** [SimplerInvoicing/validation#30]
cbc:InvoiceTypeCodeType is xsd:normalizedString.
. = 380 will give "FORG0001: invalid floating point value" if a string is used in cbc:InvoiceTypeCode and code will stop.

Possible solution . = '380'

**Comment by tjeb** [comment]
Thanks for the report, should be fixed now. Nice catch :)

**Comment by tjeb** [comment]
BTW, this also made me notice that there is another error regarding the document type code (the case where the document is a CreditNote), I have created a separate issue for that: #31
