### ISSUE TITLE
Let's just deprecate SI-1.2. It's the only Peppol BIS V2 based (Invoice) format left on the earth.

### ISSUE THREAD

**Issue by ri4a** [SimplerInvoicing/validation#38]
_Originally posted by @ri4a in https://github.com/phax/phive-rules/issues/9#issuecomment-1000532587_

And yes, I know the NPa is working on this.

**Comment by phax** [comment]
Finally it was deprecated and marked as removed in OpenPeppol:

https://docs.peppol.eu/edelivery/codelists/v8.7/Peppol%20Code%20Lists%20-%20Document%20types%20v8.7.html#75

Must not be used by 2024-01-01

**Comment by ri4a** [comment]
@tjeb is this in line with the NPa policy that SI-1.2 can still be used under mutual agreement?

**Comment by tjeb** [comment]
AFAICT after 2024-01-01 its use will be considered non-compliant by the NPA.

**Comment by ri4a** [comment]
Done!
