### ISSUE TITLE
Question on November 2023 release

### ISSUE THREAD

**Issue by phax** [SimplerInvoicing/validation#39]
Hi @tjeb quick question on the https://github.com/peppolautoriteit-nl/validation/releases/tag/2023-11-29 release: do I understand you correctly that *only* the underlying EN rules were updated but the SimplerInvoicing rules are not updated??

However, why haven't the version numbers not changed compared to the May 2023 release?
![grafik](https://github.com/peppolautoriteit-nl/validation/assets/196219/40c11782-8494-4804-afc7-f1d6e0cf61e3)

Thanks

**Comment by tjeb** [comment]
You are correct, somehow the last commit of the previous release branch (the one that updates the version number) didn't make it back to main, so this version renumbering ended up with the same version. I will pull this pre-release and fix it shortly.

Indeed, only the EN rules have been updated, and there were no other changes. The only other commit in the source is a change in the way the modified EN rule file for the g-account extension is created.

**Comment by tjeb** [comment]
And done :) Thanks for being alert.
