### ISSUE TITLE
Latest XSL files for v1.1

### ISSUE THREAD

**Issue by juskoljo** [SimplerInvoicing/validation#7]
Would it be possible to have latest XSL files (both invoice and corrective invoice/credit note) available for v1.1 release? 

Thanks,
Jussi Koljonen

**Comment by dutchcoin** [comment]
You can use the v.1.2 XSL files they are backward compatible.

Regards,
Eelko Neven

**Comment by ojundt** [comment]
Just found out that the XSL files are NOT backwards compatible. You'll find plenty of examples in https://github.com/SimplerInvoicing/testset where the 1.1 or 1.2 XSL files return different validation results for the previous generation(s).
