### ISSUE TITLE
Missing flag for some rules

### ISSUE THREAD

**Issue by wooshie** [SimplerInvoicing/validation#8]
Hi, is it correct for some rules to omit <xsl:attribute name="flag">...</xsl:attribute>, SI-V12-INV-R214 is the example?

**Comment by juskoljo** [comment]
There seems to have more than one assertion that doesn't have flag specified. I'm also wondering that should these be interpreted as warnings or fatals? @tjeb

**Comment by juskoljo** [comment]
I create a pull request https://github.com/SimplerInvoicing/validation/pull/9

**Comment by tjeb** [comment]
Thanks! I was thinking it should default to warning but it wouldn't hurt to be explicit, but it turns out there was one case in our test set where it actually resulted in an error that should have been a warning.

**Comment by tjeb** [comment]
Merged, closing issue.

**Comment by juskoljo** [comment]
Great, thanks! 👍  

PS. I realized that I didn't rebuild XSL file located in the root folder. Would it be possible you to update it?

**Comment by tjeb** [comment]
my bad, done in 0fa7bd2098a89ca8da547c01ee8ccfe42e4a2ad8

**Comment by juskoljo** [comment]
Super, thank you! :)
